### ISSUE TITLE
Fix fetch-conferences workflow issue

### ISSUE THREAD

**Issue by juvekaradheesh** [PLAN-Lab/plan-lab.github.io#4]
Fetch conferences workflow fails to fetch conferences from the google sheets, thus the conferences are not updates.

**Comment by juvekaradheesh** [comment]
@Isminoula 
https://docs.google.com/spreadsheets/d/1Z-uP86zVn0huoLXRPo9SI3klV11BQgfk/edit#gid=1146930065 
This sheet is private, cannot fetch it.

I get this message: This shared drive's settings prevent sharing with non-members

**Comment by Isminoula** [comment]
@juvekaradheesh adding @immuntasir  to fix file sharing
